####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode
#
# Before building the docker image run:
#
# mvn package -Pnative -Dquarkus.native.container-build=true
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/quarkus-lucene .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/quarkus-lucene
#
###
FROM gunnarmorling/search-morling-dev:20221120
